# Generated by Django 3.1 on 2020-08-05 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystorage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essay',
            old_name='athor',
            new_name='author',
        ),
    ]
